version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/auth/libraries/pip-auth/"
    schedule:
      interval: "daily"
    assignees:
      - "bastianjoel"
    open-pull-requests-limit: 42

  - package-ecosystem: "npm"
    directory: "/auth/"
    schedule:
      interval: "daily"
    assignees:
      - "bastianjoel"
    groups:
       typescript-eslint:
          patterns:
            - "@typescript-eslint/*"
       opentelemetry:
          patterns:
            - "@opentelemetry/*"
    open-pull-requests-limit: 42

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "bastianjoel"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "bastianjoel"
      - "rrenkert"
