FROM python:3.9.0-slim-buster

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it && \
    apt-get install -y make git curl openssl

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs

ENV LB_LIBRARY_PATH=/usr/local/lib

WORKDIR /app

# Install dependencies. the `node_modules` folder is in /app
COPY auth/package*.json ./
RUN npm install

# Application lays in /app/src
COPY ./auth ./
COPY auth/entrypoint.sh ./

# Install pip-dependencies.
RUN pip install --no-cache-dir -r ./libraries/pip-auth/requirements.txt -r ./libraries/pip-auth/requirements_development.txt

EXPOSE 9004

ENV OPENSLIDES_DEVELOPMENT 1

ENTRYPOINT [ "./entrypoint.sh" ]
CMD ["npm", "run", "dev"]
