FROM node:13

# Dockerize is needed to sync containers startup
ENV DOCKERIZE_VERSION v0.6.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

WORKDIR /app

# Install dependencies. the `node_modules` folder is in /app
COPY auth/package*.json ./
COPY auth/tsconfig.json ./
RUN npm install

# Application lays in /app/src
COPY ./auth ./
COPY ./dev-keys /tmp/keys

# Now the source-files can be transpiled
RUN npm run build
EXPOSE 9004
CMD ["npm", "run", "start"]