FROM node:18.16-alpine
ENV NODE_VERSION=18.16.1

# Install python3.8
RUN apk update
RUN apk add --no-cache python3 python3-dev py3-pip gcc libc-dev

WORKDIR /app

# Install dependencies. the `node_modules` folder is in /app
COPY auth/package*.json ./
RUN npm ci

# Install pip-dependencies.
COPY auth/libraries/pip-auth/requirements*.txt ./libraries/pip-auth/
RUN pip install --no-cache-dir -r ./libraries/pip-auth/requirements.txt -r ./libraries/pip-auth/requirements_development.txt

# Application lays in /app/src
COPY auth/.eslintrc.js ./
COPY auth/.prettierrc ./
COPY auth/entrypoint.sh ./
COPY auth/jest.config.ts ./
COPY auth/nodemon.json ./
COPY auth/tsconfig*.json ./
COPY auth/wait-for.sh ./

RUN chmod 777 -R .

EXPOSE 9004

ENV OPENSLIDES_DEVELOPMENT 1

ENTRYPOINT [ "./entrypoint.sh" ]
CMD ["npm", "run", "dev"]
