FROM node:13

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it

WORKDIR /app

# Install dependencies. the `node_modules` folder is in /app
COPY auth/package*.json ./
RUN npm install

# Application lays in /app/src
COPY ./auth ./
COPY ./dev-keys /keys

ENTRYPOINT [ "./entrypoint.test.sh" ]
CMD ["npm", "run", "test"]