FROM node:22.11-alpine
ENV NODE_VERSION=22.11.0

WORKDIR /app

# Install dependencies. the `node_modules` folder is in /app
COPY auth/package*.json ./
RUN npm ci

# Application lays in /app/src
COPY ./auth ./
COPY auth/entrypoint.sh ./

EXPOSE 9004

ENV OPENSLIDES_DEVELOPMENT 1

ENTRYPOINT ["./entrypoint.sh"]
CMD ["node", "node_modules/.bin/nodemon", "src/index.ts"]
