-- Create user table
CREATE TABLE user_t (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username varchar(256) NOT NULL,
    member_number varchar(256),
    saml_id varchar(256) CONSTRAINT minlength_saml_id CHECK (char_length(saml_id) >= 1),
    pronoun varchar(32),
    title varchar(256),
    first_name varchar(256),
    last_name varchar(256),
    is_active boolean DEFAULT True,
    is_physical_person boolean DEFAULT True,
    password varchar(256),
    default_password varchar(256),
    can_change_own_password boolean DEFAULT True,
    email varchar(256),
    default_vote_weight decimal(16,6) CONSTRAINT minimum_default_vote_weight CHECK (default_vote_weight >= 0.000001) DEFAULT '1.000000',
    last_email_sent timestamptz,
    is_demo_user boolean,
    last_login timestamptz,
    external boolean,
    gender_id integer,
    organization_management_level varchar(256) CONSTRAINT enum_user_organization_management_level CHECK (organization_management_level IN ('superadmin', 'can_manage_organization', 'can_manage_users')),
    home_committee_id integer,
    organization_id integer GENERATED ALWAYS AS (1) STORED NOT NULL
);

-- Insert test user with password 'password' hashed with argon2
-- The hash below is for password 'password'

-- INSERT INTO user_t (
--     username,
--     password,
--     email,
--     first_name,
--     last_name,
--     is_active
-- ) VALUES (
--     'admin',
--     '$argon2id$v=19$m=65536,t=3,p=4$IGvN2jGNrF5aPB5G85671w$zdaAc/BrqhD7edEz5bJroJ+M9xeZrUWao34lY8494cM',
--     'admin@example.com',
--     'Admin',
--     'User',
--     true
-- );

-- -- Insert another test user
-- INSERT INTO user_t (
--     username,
--     password,
--     email,
--     first_name,
--     last_name,
--     is_active
-- ) VALUES (
--     'testuser',
--     '$argon2id$v=19$m=65536,t=3,p=4$IGvN2jGNrF5aPB5G85671w$zdaAc/BrqhD7edEz5bJroJ+M9xeZrUWao34lY8494cM',
--     'test@example.com',
--     'Test',
--     'User',
--     true
-- );

-- -- Insert an inactive user to test authentication rejection
-- INSERT INTO user_t (
--     username,
--     password,
--     email,
--     first_name,
--     last_name,
--     is_active
-- ) VALUES (
--     'inactive',
--     '$argon2id$v=19$m=65536,t=3,p=4$IGvN2jGNrF5aPB5G85671w$zdaAc/BrqhD7edEz5bJroJ+M9xeZrUWao34lY8494cM',
--     'inactive@example.com',
--     'Inactive',
--     'User',
--     false
-- );

-- -- Create an index on username for faster lookups
-- CREATE INDEX idx_user_username ON user_t(username);
-- CREATE INDEX idx_user_active ON user_t(is_active);
