from authlib.auth_handler import AuthHandler

example_token_invalid = "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzSW4iOiIxMG0iLCJzZXNzaW9uSWQiOiI2NjUzYWMwNmJhNjVkYmQzNDE5NTQwOGQ1MDI5NjU1ZSIsInVzZXJJZCI6MSwiaWF0IjoxNTk3MTQ5NDI0LCJleHAiOjE1OTcxNTAwMjR9.z21-bSIj_xZAoCbwXTqqf_ODAIEbbeSehYIE33dmYUs"
example_cookie_invalid = "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzSW4iOiIxMG0iLCJzZXNzaW9uSWQiOiI2NjUzYWMwNmJhNjVkYmQzNDE5NTQwOGQ1MDI5NjU1ZSIsInVzZXJJZCI6MSwiaWF0IjoxNTk3MTQ5NDI0LCJleHAiOjE1OTcxNTAwMjR9.z21-bSIj_xZAoCbwXTqqf_ODAIEbbeSehYIE33dmYUs"

example_token = "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiI1Y2UyYzE0NThjYWI0NzIzMGQ5NjUwZWZjMmU4YWEwNCIsInVzZXJJZCI6MSwiaWF0IjoxNTk5NDY3ODA3fQ.wefZbgc_095Cob_2z8Q-iD03-X5NDeXqkl5Mgx68Mq4"
example_cookie = "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiI1Y2UyYzE0NThjYWI0NzIzMGQ5NjUwZWZjMmU4YWEwNCIsImlhdCI6MTU5OTQ2NjI4Nn0.V-Uu-DM9wb6yXKmn371pqAa-3QIdR4GClYJiYhZDkzw"

example_token_expired = "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzSW4iOiIxMG0iLCJzZXNzaW9uSWQiOiI2NjUzYWMwNmJhNjVkYmQzNDE5NTQwOGQ1MDI5NjU1ZSIsInVzZXJJZCI6MSwiaWF0IjoxNTk3MTQ5NDI0LCJleHAiOjE1OTcxNTAwMjR9.z21-bSIj_xZAoCbwXTqqf_ODAIEbbeSehYIE33dmYUs"

auth_handler = AuthHandler("https://auth:9004")


def test_authenticate_invalid_token_cookie():
    return auth_handler.authenticate(example_token_invalid, example_cookie_invalid)


def test_authenticate():
    return auth_handler.authenticate(example_token, example_cookie)


def test_authenticate_expired_token():
    return auth_handler.authenticate(example_token_expired, example_cookie)


if __name__ == "__main__":
    test_authenticate()
    test_authenticate_invalid_token_cookie()
