AUTHENTICATION_HEADER = "authentication"
AUTHORIZATION_HEADER = "authorization"
COOKIE_NAME = "refreshId"
USER_ID_PROPERTY = "userId"
SESSION_ID_PROPERTY = "sid"
ANONYMOUS_USER = 0

PASSWORD_RESET_TOKEN_EXPIRATION_TIME = 600
